### ISSUE TITLE
"Cannot found f3read/f3write."

### ISSUE THREAD

**Issue by kalsan** [zwpwjwtz/f3-qt#1]
I'm running Arch Linux and I have installed f3read and all other f3* programs under `/usr/bin`. Nevertheless, f3-qt (sitting in the `Downloads/f3-qt` repo and comiled with `qmake` and `make`, launched with `./f3-qt`) will not startup. Instead it claims that I have no f3 installed.

**Comment by zwpwjwtz** [comment]
f3-qt depends on f3. For Archlinux user, please compile and install f3 first (https://aur.archlinux.org/packages/f3-git/).
Also, thanks for point out this grammatical error :)

**Comment by kalsan** [comment]
Thanks for your answer. As stated above,  I do have f3 installed. I actually used the AUR Repo that you pointed to.

**Comment by zwpwjwtz** [comment]
That's really strange. I use Manjaro (derived from Arch) myself, and I don't have the same issue.

I just downloaded an Arch ISO Image (archlinux-2017.01.01-dual.iso), installed it on virtualbox using 64-bit mode, then installed qt5-base, xorg-server, plasma-desktop, etc. After I have compiled and installed both f3 and f3-qt, the GUI can be launched successfully without warning.

Could you please switch to the directory that contains f3-qt (executable), then try to run f3read without specify the directory (i.e "f3read" instead of "/usr/bin/f3read"), and paste the output?

**Comment by kalsan** [comment]
Like this?

(where `filename*` means that `filename` is executable; and `$` means that I execute a command as non-super-user)
```
$ cd f3-qt/
$ ls
advanced.png     f3_launcher.h  f3-qt.pro.user  helpwindow.h   main.cpp        Makefile             moc_mainwindow.o
back.png         f3_launcher.o  f3read*         helpwindow.o   main.o          moc_f3_launcher.cpp  qrc_icon.cpp
close.png        f3.png         f3write*        helpwindow.ui  mainwindow.cpp  moc_f3_launcher.o    qrc_icon.o
f3brew*          f3probe*       f3write.h2w*    icon.qrc       mainwindow.h    moc_helpwindow.cpp   README.md
f3fix*           f3-qt*         help.png        INSTALL        mainwindow.o    moc_helpwindow.o     ui_helpwindow.h
f3_launcher.cpp  f3-qt.pro      helpwindow.cpp  LICENSE        mainwindow.ui   moc_mainwindow.cpp   ui_mainwindow.h
$ ./f3-qt      [=> Cannot found ...; press ok]
$ f3read
F3 read 6.0
Copyright (C) 2010 Digirati Internet LTDA.
This is free software; see the source for copying conditions.

Usage: f3read [--start-at=NUM] [--end-at=NUM] <PATH>
$ whereis f3read
f3read: /usr/bin/f3read /usr/share/man/man1/f3read.1.gz
```

**Comment by zwpwjwtz** [comment]
Try to apply this patch for debug, then see if there is any userful output.
[debug_patch.txt](https://github.com/zwpwjwtz/f3-qt/files/719122/debug_patch.txt)

**Comment by kalsan** [comment]
Thank you for your commitment. The message says: `Probing for F3 failed. ErrMsg: Version number is 0`.

Running `f3probe --version` yields: `F3 Probe 6.0`

**Comment by zwpwjwtz** [comment]
Fixed in 9445116 .
It seems that you are using the original 6.0 version of f3, which does not support display of scanning progress. It is recommended to use "f3-git" (rather than "f3") from AUR.

**Comment by kalsan** [comment]
Very nice, thanks a lot! And cool solution with the warning ^^

**Comment by kalsan** [comment]
Btw I brought f3-qt to AUR: https://aur.archlinux.org/packages/f3-qt-git/

**Comment by zwpwjwtz** [comment]
Pretty much thanks!
