### ISSUE TITLE
Text on main window doesn't quite fit

### ISSUE THREAD

**Issue by bobpaul** [zwpwjwtz/f3-qt#11]
Observed on e9c251b. 

![image](https://user-images.githubusercontent.com/90864/67626359-f9c2c580-f80f-11e9-891a-682a497c5dab.png)

I'm using xfce4 and installed via the [f3-qt-git AUR package](https://aur.archlinux.org/packages/f3-qt-git/). Maybe I'm missing a required font?

**Comment by zwpwjwtz** [comment]
Texts rendered with different GUI kit (Gtk, Qt, wx) behave differently. Thus it is hard to make it compatible for all desktops.
You can try to reduce the text size though.

**Comment by zwpwjwtz** [comment]
Fixed in 5087e1f.
