### ISSUE TITLE
Please provide a screenshot

### ISSUE THREAD

**Issue by brunetton** [zwpwjwtz/f3-qt#16]
Hi,

Thank you for the project ! I would have been interested on having a (or more) screenshots of this soft in the README to quickly see how it looks.
(I'd probably do it and address a PR by the way)

**Comment by zwpwjwtz** [comment]
Fixed in [95b5837](https://github.com/zwpwjwtz/f3-qt/commit/95b5837f48bb909a34d2d2d80efc84565f1a7850).

**Comment by brunetton** [comment]
Thanks. I opened [a PR](https://github.com/zwpwjwtz/f3-qt/pull/20) to add it to README. I thought it was obvious ;)
