### ISSUE TITLE
qt dependency unavailable.

### ISSUE THREAD

**Issue by illogicgated** [zwpwjwtz/f3-qt#18]
You can no longer install "qt5-default" under KUbuntu 22.04.

This causes failure at step 1 of the build instructions for qmake.

Total failure for something that should be distributed as a binary.

**Comment by R8s6** [comment]
i don't use ubuntu, but please try `qt6-default` (or a similar one on ubuntu) maybe?

**Comment by zwpwjwtz** [comment]
Fixed in [95b5837](https://github.com/zwpwjwtz/f3-qt/commit/95b5837f48bb909a34d2d2d80efc84565f1a7850).
