### ISSUE TITLE
fix percentage label in progress

### ISSUE THREAD

**Issue by johndoe71rus** [zwpwjwtz/f3-qt#19]
version 2.1.0
fix percentage label in progress 
short video

https://github.com/zwpwjwtz/f3-qt/assets/7861172/9ff270dc-f4af-4b39-ab6e-3cf97bbf0912

**Comment by zwpwjwtz** [comment]
Thanks for the feedback. I'll take time to reorganize the layout.

**Comment by zwpwjwtz** [comment]
Fixed in 5087e1f.

**Comment by johndoe71rus** [comment]
Think need fix progress bar to

https://github.com/zwpwjwtz/f3-qt/assets/7861172/e6928cc3-7553-406e-8e16-f9f7ef2c8be5
