### ISSUE TITLE
fix result window

### ISSUE THREAD

**Issue by johndoe71rus** [zwpwjwtz/f3-qt#3]
Think need fix result window
[https://postimg.org/image/ocqmx8qvt](https://postimg.org/image/ocqmx8qvt)

lubuntu 14.04.

**Comment by zwpwjwtz** [comment]
Confirmed.
This seems to be a common problem in many non-Qt-based desktop (LXDE, Unity and Cinnamon).
I'm trying to find if it is a dependency related issue, or it simply lacks some properties.

**Comment by zwpwjwtz** [comment]
Fixed in 6af166b.
