### ISSUE TITLE
Run script

### ISSUE THREAD

**Issue by johndoe71rus** [zwpwjwtz/f3-qt#5]
Please, add simple run script file. Put binary f3-qt to any directory with f3 binary. Search not only path directory

**Comment by zwpwjwtz** [comment]
Could you please describe the meaning of "run script file"? I cannot figure out the exact functionaltiy that you want.
Perhaps you wish to specify the path where binary f3-qt is located?

**Comment by johndoe71rus** [comment]
i take this from other program and remove some.
http://paste.ubuntu.com/24307115/
i don't shure that's all correct.
i copy this file and f3-qt binary to folder with f3 binary. And run script.

**Comment by zwpwjwtz** [comment]
I guess this is what you want: c9b9780

**Comment by johndoe71rus** [comment]
yep. Thanks

**Comment by johndoe71rus** [comment]
i put latest git binary f3* and f3-qt to ~/bin/f3 folder. It run, but don't start test. Progress move left to right and back. Files don't create. 
f3* binary work with terminal command.

**Comment by zwpwjwtz** [comment]
Which mode (basic mode or advanced mode) were you in when doing the test?
Also, can you provide your device type (hard disk, flash disk or memory disk) as well as device path (something like "/dev/sdb1" or "/media/user/Disk")?

**Comment by johndoe71rus** [comment]
basic mode, flash disk "/media/user/%lable%"

**Comment by johndoe71rus** [comment]
advanced mode don't work too. button "stop" don't work in both mode. work only exit. And please fix window 
https://postimg.org/image/6whmpk42d/

lubuntu 14.04.5

**Comment by zwpwjwtz** [comment]
Can you provide the output of terminal command of f3?
The window problem should have already been fixed in #3 . But there might be something broken again due to the update of Qt library. I'll test it when possible.

**Comment by johndoe71rus** [comment]
> ~/bin/f3$ ./f3-qt
QMetaObject::connectSlotsByName: No matching signal for on_timer_timeout()
QMetaObject::connectSlotsByName: No matching signal for on_cui_status_changed(f3_launcher_status)
QMetaObject::connectSlotsByName: No matching signal for on_cui_error(f3_launcher_error_code)

but then i rebuild with clean sources https://paste.ubuntu.com/p/g7wRphJtHr/
size little different. and no err or message to console output. And don't work

**Comment by zwpwjwtz** [comment]
I mean the terminal output of f3read or f3write, not f3-qt.
Also, the output of f3-qt that you provided shows obviously that your local repository is not up-to-date with github.com (because these error messages have been suppressed in the latest version). Please re-clone this repository (git@github.com:zwpwjwtz/f3-qt.git), or execute "git pull" to update the repository, then rebuild it.

**Comment by johndoe71rus** [comment]
maybe the binary was old. I updated the repository yesterday. Above cited the log cleanup of the repository f3-qt and binaries rebuild. And i  make clean and rebuilt f3 and extra.

f3write log https://paste.ubuntu.com/p/gsSrDgZW6Q/

**Comment by zwpwjwtz** [comment]
Does f3-qt now works properly (after rebuild)?
If not, please re-run f3write in terminal with following command:
``f3write -p 1 [path]``
and see if it shows any number (or percentage) related to current progress.

**Comment by johndoe71rus** [comment]
https://postimg.org/image/581he18w5/
f3write work
f3-qt don't work,

**Comment by zwpwjwtz** [comment]
Fixed in 157d962.

**Comment by johndoe71rus** [comment]
thanks.
Little cosmetic fix https://imgur.com/iwI5RIF

in advanced mode button "Open", not "Choose" in dialog. Only can paste path to disk. 
in default mode stage 2, does not show progress. symbol '?' Instead '\|/-'
