### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by johndoe71rus** [zwpwjwtz/f3-qt#7]
try build latest version 

> 
/programs/f3-qt$ make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic helpwindow.ui -o ui_helpwindow.h
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=\"2.1.0\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:8:32: error: ‘AA_EnableHighDpiScaling’ is not a member of ‘Qt’
     QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
 ^
make: *** [main.o] Error 1

**Comment by zwpwjwtz** [comment]
I added the constant "AA_EnableHighDpiScaling" in the latest version to enable HiDPI scaling by default, and it is supposed to work on all platform with Qt version >=5.6.
Could you please provide some information about your OS and the version of the Qt library that you are using?

**Comment by johndoe71rus** [comment]
lubuntu 14.04.5
qt5-default 5.5.1+dfsg-16.5ppa1~trusty1 from http://ppa.launchpad.net/kvirc/kvirc-qt5.5/ubuntu/
some qt4-* 4:4.8.5+git... packages from ubuntu repository 
any more info?

**Comment by zwpwjwtz** [comment]
Ok, I understand. Ubuntu trusty has a older Qt version that does not support "AA_EnableHighDpiScaling".
Fixed in bf8cddf.
